load('MixtureData.mat');
%Set number of components.
K = 3;
%Fir Guassian mixture distribution using the EM algorithm.
GMModel = fitgmdist(V,K);
% Posterior probabiities of each data sample to be generated by 
% each component.
P = posterior(GMModel,V);
% Estimated means, covariances and mixing coefficients of each
% component.
MixtureMeans = GMModel.mu;
MixtureCovariances = GMModel.Sigma;
MixtureProportions = GMModel.PComponents;
for k =1:K
    k
    MixtureMeans(k,:)
    MixtureCovariances(:,:,k)
    MixtureProportions(k)
end
% Colour coordinated plot for K=2 or K=3. The posterior probabilities 
% are interpreted as red, green, blue colour proportions.
% If k=2, the blue proportion is set to zero.
if K==2 || K==3
    if K == 2
        P = cat(2,P, zeros(length(P),1));
    end
    figure;
    scatter(V(:,1), V(:,2),10,P,'filled');
end
